# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Desktop/Duo-Game-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Desktop/Duo-Game-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Desktop/Duo-Game-Engine/CMakeFiles /home/alex/Desktop/Duo-Game-Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Desktop/Duo-Game-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named output

# Build rule for target.
output: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output
.PHONY : output

# fast build rule for target.
output/fast:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/build
.PHONY : output/fast

#=============================================================================
# Target rules for targets named engine_lib

# Build rule for target.
engine_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_lib
.PHONY : engine_lib

# fast build rule for target.
engine_lib/fast:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/build
.PHONY : engine_lib/fast

source/gameObject/DUO-GameObject.o: source/gameObject/DUO-GameObject.cpp.o

.PHONY : source/gameObject/DUO-GameObject.o

# target to build an object file
source/gameObject/DUO-GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-GameObject.cpp.o
.PHONY : source/gameObject/DUO-GameObject.cpp.o

source/gameObject/DUO-GameObject.i: source/gameObject/DUO-GameObject.cpp.i

.PHONY : source/gameObject/DUO-GameObject.i

# target to preprocess a source file
source/gameObject/DUO-GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-GameObject.cpp.i
.PHONY : source/gameObject/DUO-GameObject.cpp.i

source/gameObject/DUO-GameObject.s: source/gameObject/DUO-GameObject.cpp.s

.PHONY : source/gameObject/DUO-GameObject.s

# target to generate assembly for a file
source/gameObject/DUO-GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-GameObject.cpp.s
.PHONY : source/gameObject/DUO-GameObject.cpp.s

source/gameObject/DUO-GameObjectComponent.o: source/gameObject/DUO-GameObjectComponent.cpp.o

.PHONY : source/gameObject/DUO-GameObjectComponent.o

# target to build an object file
source/gameObject/DUO-GameObjectComponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-GameObjectComponent.cpp.o
.PHONY : source/gameObject/DUO-GameObjectComponent.cpp.o

source/gameObject/DUO-GameObjectComponent.i: source/gameObject/DUO-GameObjectComponent.cpp.i

.PHONY : source/gameObject/DUO-GameObjectComponent.i

# target to preprocess a source file
source/gameObject/DUO-GameObjectComponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-GameObjectComponent.cpp.i
.PHONY : source/gameObject/DUO-GameObjectComponent.cpp.i

source/gameObject/DUO-GameObjectComponent.s: source/gameObject/DUO-GameObjectComponent.cpp.s

.PHONY : source/gameObject/DUO-GameObjectComponent.s

# target to generate assembly for a file
source/gameObject/DUO-GameObjectComponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-GameObjectComponent.cpp.s
.PHONY : source/gameObject/DUO-GameObjectComponent.cpp.s

source/gameObject/DUO-Scene.o: source/gameObject/DUO-Scene.cpp.o

.PHONY : source/gameObject/DUO-Scene.o

# target to build an object file
source/gameObject/DUO-Scene.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-Scene.cpp.o
.PHONY : source/gameObject/DUO-Scene.cpp.o

source/gameObject/DUO-Scene.i: source/gameObject/DUO-Scene.cpp.i

.PHONY : source/gameObject/DUO-Scene.i

# target to preprocess a source file
source/gameObject/DUO-Scene.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-Scene.cpp.i
.PHONY : source/gameObject/DUO-Scene.cpp.i

source/gameObject/DUO-Scene.s: source/gameObject/DUO-Scene.cpp.s

.PHONY : source/gameObject/DUO-Scene.s

# target to generate assembly for a file
source/gameObject/DUO-Scene.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-Scene.cpp.s
.PHONY : source/gameObject/DUO-Scene.cpp.s

source/gameObject/DUO-Utils.o: source/gameObject/DUO-Utils.cpp.o

.PHONY : source/gameObject/DUO-Utils.o

# target to build an object file
source/gameObject/DUO-Utils.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-Utils.cpp.o
.PHONY : source/gameObject/DUO-Utils.cpp.o

source/gameObject/DUO-Utils.i: source/gameObject/DUO-Utils.cpp.i

.PHONY : source/gameObject/DUO-Utils.i

# target to preprocess a source file
source/gameObject/DUO-Utils.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-Utils.cpp.i
.PHONY : source/gameObject/DUO-Utils.cpp.i

source/gameObject/DUO-Utils.s: source/gameObject/DUO-Utils.cpp.s

.PHONY : source/gameObject/DUO-Utils.s

# target to generate assembly for a file
source/gameObject/DUO-Utils.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/gameObject/DUO-Utils.cpp.s
.PHONY : source/gameObject/DUO-Utils.cpp.s

source/graphics/DUO-Graphics.o: source/graphics/DUO-Graphics.cpp.o

.PHONY : source/graphics/DUO-Graphics.o

# target to build an object file
source/graphics/DUO-Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/graphics/DUO-Graphics.cpp.o
.PHONY : source/graphics/DUO-Graphics.cpp.o

source/graphics/DUO-Graphics.i: source/graphics/DUO-Graphics.cpp.i

.PHONY : source/graphics/DUO-Graphics.i

# target to preprocess a source file
source/graphics/DUO-Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/graphics/DUO-Graphics.cpp.i
.PHONY : source/graphics/DUO-Graphics.cpp.i

source/graphics/DUO-Graphics.s: source/graphics/DUO-Graphics.cpp.s

.PHONY : source/graphics/DUO-Graphics.s

# target to generate assembly for a file
source/graphics/DUO-Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/graphics/DUO-Graphics.cpp.s
.PHONY : source/graphics/DUO-Graphics.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/maths/DUO-AABB.o: source/maths/DUO-AABB.cpp.o

.PHONY : source/maths/DUO-AABB.o

# target to build an object file
source/maths/DUO-AABB.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-AABB.cpp.o
.PHONY : source/maths/DUO-AABB.cpp.o

source/maths/DUO-AABB.i: source/maths/DUO-AABB.cpp.i

.PHONY : source/maths/DUO-AABB.i

# target to preprocess a source file
source/maths/DUO-AABB.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-AABB.cpp.i
.PHONY : source/maths/DUO-AABB.cpp.i

source/maths/DUO-AABB.s: source/maths/DUO-AABB.cpp.s

.PHONY : source/maths/DUO-AABB.s

# target to generate assembly for a file
source/maths/DUO-AABB.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-AABB.cpp.s
.PHONY : source/maths/DUO-AABB.cpp.s

source/maths/DUO-Maths.o: source/maths/DUO-Maths.cpp.o

.PHONY : source/maths/DUO-Maths.o

# target to build an object file
source/maths/DUO-Maths.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-Maths.cpp.o
.PHONY : source/maths/DUO-Maths.cpp.o

source/maths/DUO-Maths.i: source/maths/DUO-Maths.cpp.i

.PHONY : source/maths/DUO-Maths.i

# target to preprocess a source file
source/maths/DUO-Maths.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-Maths.cpp.i
.PHONY : source/maths/DUO-Maths.cpp.i

source/maths/DUO-Maths.s: source/maths/DUO-Maths.cpp.s

.PHONY : source/maths/DUO-Maths.s

# target to generate assembly for a file
source/maths/DUO-Maths.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-Maths.cpp.s
.PHONY : source/maths/DUO-Maths.cpp.s

source/maths/DUO-Vector2.o: source/maths/DUO-Vector2.cpp.o

.PHONY : source/maths/DUO-Vector2.o

# target to build an object file
source/maths/DUO-Vector2.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-Vector2.cpp.o
.PHONY : source/maths/DUO-Vector2.cpp.o

source/maths/DUO-Vector2.i: source/maths/DUO-Vector2.cpp.i

.PHONY : source/maths/DUO-Vector2.i

# target to preprocess a source file
source/maths/DUO-Vector2.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-Vector2.cpp.i
.PHONY : source/maths/DUO-Vector2.cpp.i

source/maths/DUO-Vector2.s: source/maths/DUO-Vector2.cpp.s

.PHONY : source/maths/DUO-Vector2.s

# target to generate assembly for a file
source/maths/DUO-Vector2.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/maths/DUO-Vector2.cpp.s
.PHONY : source/maths/DUO-Vector2.cpp.s

source/runtime/DUO-Keyboard.o: source/runtime/DUO-Keyboard.cpp.o

.PHONY : source/runtime/DUO-Keyboard.o

# target to build an object file
source/runtime/DUO-Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/runtime/DUO-Keyboard.cpp.o
.PHONY : source/runtime/DUO-Keyboard.cpp.o

source/runtime/DUO-Keyboard.i: source/runtime/DUO-Keyboard.cpp.i

.PHONY : source/runtime/DUO-Keyboard.i

# target to preprocess a source file
source/runtime/DUO-Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/runtime/DUO-Keyboard.cpp.i
.PHONY : source/runtime/DUO-Keyboard.cpp.i

source/runtime/DUO-Keyboard.s: source/runtime/DUO-Keyboard.cpp.s

.PHONY : source/runtime/DUO-Keyboard.s

# target to generate assembly for a file
source/runtime/DUO-Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/runtime/DUO-Keyboard.cpp.s
.PHONY : source/runtime/DUO-Keyboard.cpp.s

source/runtime/DUO-application.o: source/runtime/DUO-application.cpp.o

.PHONY : source/runtime/DUO-application.o

# target to build an object file
source/runtime/DUO-application.cpp.o:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/runtime/DUO-application.cpp.o
.PHONY : source/runtime/DUO-application.cpp.o

source/runtime/DUO-application.i: source/runtime/DUO-application.cpp.i

.PHONY : source/runtime/DUO-application.i

# target to preprocess a source file
source/runtime/DUO-application.cpp.i:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/runtime/DUO-application.cpp.i
.PHONY : source/runtime/DUO-application.cpp.i

source/runtime/DUO-application.s: source/runtime/DUO-application.cpp.s

.PHONY : source/runtime/DUO-application.s

# target to generate assembly for a file
source/runtime/DUO-application.cpp.s:
	$(MAKE) -f CMakeFiles/engine_lib.dir/build.make CMakeFiles/engine_lib.dir/source/runtime/DUO-application.cpp.s
.PHONY : source/runtime/DUO-application.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... output"
	@echo "... engine_lib"
	@echo "... source/gameObject/DUO-GameObject.o"
	@echo "... source/gameObject/DUO-GameObject.i"
	@echo "... source/gameObject/DUO-GameObject.s"
	@echo "... source/gameObject/DUO-GameObjectComponent.o"
	@echo "... source/gameObject/DUO-GameObjectComponent.i"
	@echo "... source/gameObject/DUO-GameObjectComponent.s"
	@echo "... source/gameObject/DUO-Scene.o"
	@echo "... source/gameObject/DUO-Scene.i"
	@echo "... source/gameObject/DUO-Scene.s"
	@echo "... source/gameObject/DUO-Utils.o"
	@echo "... source/gameObject/DUO-Utils.i"
	@echo "... source/gameObject/DUO-Utils.s"
	@echo "... source/graphics/DUO-Graphics.o"
	@echo "... source/graphics/DUO-Graphics.i"
	@echo "... source/graphics/DUO-Graphics.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/maths/DUO-AABB.o"
	@echo "... source/maths/DUO-AABB.i"
	@echo "... source/maths/DUO-AABB.s"
	@echo "... source/maths/DUO-Maths.o"
	@echo "... source/maths/DUO-Maths.i"
	@echo "... source/maths/DUO-Maths.s"
	@echo "... source/maths/DUO-Vector2.o"
	@echo "... source/maths/DUO-Vector2.i"
	@echo "... source/maths/DUO-Vector2.s"
	@echo "... source/runtime/DUO-Keyboard.o"
	@echo "... source/runtime/DUO-Keyboard.i"
	@echo "... source/runtime/DUO-Keyboard.s"
	@echo "... source/runtime/DUO-application.o"
	@echo "... source/runtime/DUO-application.i"
	@echo "... source/runtime/DUO-application.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

